/**
 * TechShare Design System - UI Strings Dictionary
 * 
 * QUY CHUẨN CHỐNG HARDCODE (NO HARDCODING RULE):
 * Toàn bộ chuỗi văn bản (Tiếng Việt/Tiếng Anh), nhãn nút, tiêu đề modal,
 * thông báo lỗi, gợi ý placeholder được tập trung tại đây.
 */

export const STRINGS = {
  // Chuỗi dùng chung (Common)
  common: {
    loading: 'Đang tải...',
    processing: 'Đang xử lý...',
    refresh: 'Làm mới',
    refreshing: 'Đang làm mới...',
    search: 'Tìm kiếm',
    close: 'Đóng',
    confirm: 'Xác nhận',
    cancel: 'Hủy bỏ',
    delete: 'Xóa',
    edit: 'Chỉnh sửa',
    save: 'Lưu thay đổi',
    viewDetails: 'Chi tiết',
    actions: 'Hành động',
    status: 'Trạng thái',
    all: 'Tất cả',
    emptyList: 'Danh sách rỗng',
    notFound: 'Không tìm thấy dữ liệu phù hợp',
    phone: 'Số điện thoại',
    email: 'Email',
    address: 'Địa chỉ',
    date: 'Ngày',
    day: 'ngày',
    vnd: 'đ',
  },

  // Phân hệ Admin Dashboard
  admin: {
    dashboard: {
      brandTitle: 'TechShare Hub',
      brandSubtitle: 'Quản trị hệ thống',
      searchPlaceholder: 'Tìm kiếm nhanh đơn hàng, người dùng, sản phẩm...',
      atlasSynced: 'Đã đồng bộ Atlas',
      justNow: 'Vừa xong',
      adminRole: 'System Admin',
      adminName: 'Trần Nhật',
      overviewTab: 'Tổng quan hệ thống',
      devicesTab: 'Kiểm duyệt thiết bị',
      usersTab: 'Người dùng & Tín nhiệm',
      ekycTab: 'Xét duyệt eKYC',
      settingsTab: 'Cài đặt hệ thống',
    },

    overview: {
      title: 'Tổng quan Hệ thống TechShare',
      subtitle: 'Dữ liệu thời gian thực được đồng bộ trực tiếp từ MongoDB Atlas',
      totalRevenue: 'Tổng doanh thu sàn',
      activeOrders: 'Đơn thuê hoạt động',
      totalDevices: 'Tổng thiết bị trên sàn',
      activeUsers: 'Người dùng đang hoạt động',
      pendingEkyc: 'Hồ sơ eKYC chờ duyệt',
      revenueChartTitle: 'Biến động Doanh thu & Giao dịch',
      timeRanges: {
        '7d': '7 ngày qua',
        month: 'Tháng này',
        year: 'Năm nay',
      },
      categoryDistributionTitle: 'Phân bổ Thiết bị',
      platformWide: 'Toàn sàn',
      totalOrdersPrefix: 'Số giao dịch:',
      totalOrdersSuffix: 'lượt thuê',
      deviceUnit: 'thiết bị',
    },

    devices: {
      title: 'Kiểm duyệt Thiết bị trên Sàn',
      searchPlaceholder: 'Tìm theo Tên thiết bị, Hãng, Chủ máy...',
      categories: {
        all: 'Tất cả',
        smartphone: 'Smartphone',
        laptop: 'Laptop',
        camera: 'Máy ảnh',
        drone: 'Flycam',
        audio: 'Âm thanh',
        gaming: 'Gaming',
        accessory: 'Phụ kiện',
      },
      table: {
        colDevice: 'Thiết bị',
        colCategory: 'Danh mục',
        colOwner: 'Chủ thiết bị',
        colPrice: 'Giá thuê',
        colStatus: 'Trạng thái',
        colActions: 'Hành động',
        viewSpecsBtn: 'Specs',
        deleteBtn: 'Gỡ bỏ',
        emptyMessage: 'Không có thiết bị nào phù hợp với bộ lọc hiện tại.',
      },
      status: {
        available: 'Sẵn sàng',
        rented: 'Đang cho thuê',
        maintenance: 'Bảo trì',
        pending: 'Chờ duyệt',
      },
      modalSpecs: {
        title: 'Thông số kỹ thuật & Chi tiết thiết bị',
        partnerOwner: 'Đối tác TechShare',
        ownerPrefix: 'Chủ thiết bị:',
        depositLabel: 'Tiền cọc thiết bị',
        ratingLabel: 'Đánh giá trung bình',
        reviewsSuffix: 'lượt',
        specsTitle: 'Thông số kỹ thuật chính:',
        descriptionTitle: 'Mô tả sản phẩm:',
        noDescription: 'Chưa có thông tin mô tả chi tiết từ chủ sở hữu.',
        closeBtn: 'Đóng',
      },
      modalDelete: {
        title: 'Xác nhận gỡ bỏ thiết bị',
        warningTitle: 'Hành động này không thể hoàn tác!',
        warningMessage: 'Thiết bị này sẽ bị ẩn vĩnh viễn khỏi danh mục hiển thị cho khách thuê trên toàn hệ sinh thái TechShare.',
        cancelBtn: 'Hủy bỏ',
        confirmBtn: 'Gỡ bỏ ngay',
        deleting: 'Đang gỡ bỏ...',
      },
      toasts: {
        fetchFailed: 'Không thể kết nối đến máy chủ lấy danh sách thiết bị!',
        deleteSuccess: 'Đã gỡ bỏ thiết bị thành công khỏi sàn!',
        deleteFailed: 'Gỡ bỏ thiết bị thất bại. Vui lòng thử lại!',
      },
    },

    users: {
      title: 'Quản lý Người dùng & Tín nhiệm',
      searchPlaceholder: 'Tìm theo Tên, Email, SĐT...',
      roles: {
        all: 'Tất cả vai trò',
        admin: 'Quản trị viên',
        owner: 'Chủ thiết bị',
        renter: 'Khách thuê',
        both: 'Chủ & Khách',
      },
      table: {
        colMember: 'Thành viên',
        colRole: 'Vai trò',
        colTrustScore: 'Điểm tín nhiệm',
        colStatus: 'Trạng thái',
        colActions: 'Hành động',
        detailBtn: 'Chi tiết',
        lockBtn: 'Khóa',
        unlockBtn: 'Mở khóa',
        verifiedBadge: 'Tài khoản đã hoàn tất xác thực eKYC CCCD',
        trustScoreTitle: 'Điểm tín nhiệm:',
        activeStatus: 'Hoạt động',
        lockedStatus: 'Đã khóa',
        emptyMessage: 'Không tìm thấy người dùng nào phù hợp.',
      },
      modalWallet: {
        title: 'Hồ sơ Tài chính & Tín nhiệm Escrow',
        availableBalance: 'Số dư ví khả dụng',
        heldBalance: 'Số dư ký quỹ giữ (Hold)',
        trustScoreTitle: 'Điểm tín nhiệm Escrow',
        verifiedStatus: 'Đã xác thực danh tính eKYC CCCD',
        unverifiedStatus: 'Chưa hoàn tất eKYC',
      },
      modalLock: {
        titleLock: 'Khóa tài khoản người dùng',
        titleUnlock: 'Mở khóa tài khoản người dùng',
        warningLock: 'Bạn có chắc chắn muốn KHÓA tài khoản này? Người dùng sẽ không thể đăng nhập hoặc tạo giao dịch thuê.',
        warningUnlock: 'Bạn có chắc chắn muốn MỞ KHÓA tài khoản này để người dùng tiếp tục hoạt động?',
      },
      toasts: {
        fetchFailed: 'Không thể lấy dữ liệu người dùng!',
        lockSuccess: 'Đã khóa tài khoản thành công!',
        unlockSuccess: 'Đã mở khóa tài khoản thành công!',
        actionFailed: 'Thao tác thất bại, vui lòng thử lại!',
      },
    },

    ekyc: {
      title: 'Xét duyệt Hồ sơ eKYC Cấp Tích Xanh',
      tabs: {
        pending: 'Chờ duyệt',
        approved: 'Đã duyệt',
        rejected: 'Đã từ chối',
        all: 'Tất cả',
      },
      emptyState: {
        title: 'Không có hồ sơ nào cần duyệt',
        loadingTitle: 'Đang tải danh sách hồ sơ...',
        description: 'Tất cả yêu cầu xác thực danh tính công dân đều đã được xử lý xong.',
      },
      card: {
        idCardPrefix: 'Số CCCD:',
        phonePrefix: 'SĐT:',
        emailPrefix: 'Email:',
        submittedDatePrefix: 'Ngày gửi:',
        frontLabel: '1. Mặt trước CCCD',
        backLabel: '2. Mặt sau CCCD',
        selfieLabel: '3. Chân dung cầm CCCD',
        approveBtn: 'Duyệt & Cấp Tích Xanh',
        rejectBtn: 'Từ chối',
      },
      modalReject: {
        title: 'Từ chối hồ sơ xác thực eKYC',
        reasonPrompt: 'Vui lòng chọn hoặc nhập lý do từ chối để gửi thông báo hướng dẫn lại cho người dùng:',
        customReasonPlaceholder: 'Nhập lý do cụ thể khác nếu cần...',
        cancelBtn: 'Đóng',
        confirmBtn: 'Xác nhận Từ chối',
      },
      reasons: [
        'Hình ảnh CCCD bị mờ, lóa sáng hoặc thông tin không rõ nét.',
        'Ảnh chân dung Selfie không khớp với khuôn mặt trên CCCD.',
        'Số CCCD hoặc thông tin họ tên không trùng khớp với hồ sơ đăng ký.',
        'Ảnh giấy tờ bị cắt góc, có dấu hiệu chỉnh sửa hoặc không hợp lệ.',
      ],
      toasts: {
        fetchFailed: 'Không thể tải danh sách hồ sơ eKYC!',
        approveSuccess: 'Đã duyệt hồ sơ và cấp tích xanh thành công cho',
        approveFailed: 'Phê duyệt hồ sơ thất bại!',
        rejectSuccess: 'Đã từ chối hồ sơ của',
        rejectFailed: 'Từ chối hồ sơ thất bại!',
      },
    },
  },

  // Phân hệ Owner Hub (Chủ thiết bị)
  owner: {
    sidebar: {
      brandTitle: 'TechShare Owner',
      brandSubtitle: 'Không gian Chủ máy',
      overviewTab: 'Tổng quan & KPI',
      devicesTab: 'Kho máy của tôi',
      bookingsTab: 'Xử lý yêu cầu thuê',
      calendarTab: 'Lịch bận cá nhân',
      analyticsTab: 'Báo cáo doanh thu',
      walletTab: 'Ví ký quỹ Escrow',
      switchClientBtn: 'Trang chủ khách thuê',
      logoutBtn: 'Đăng xuất',
      ownerName: 'Nguyễn Kiên / Nhật',
      ownerRole: 'Đối tác Chủ thiết bị',
      verifiedBadge: 'Tích xanh eKYC',
    },

    overview: {
      title: 'Tổng quan Hoạt động Cho thuê',
      subtitle: 'Theo dõi hiệu suất kinh doanh, quản lý kho máy và xử lý các yêu cầu thuê tức thì',
      kpis: {
        totalDevices: 'Tổng thiết bị',
        activeRentals: 'Đang cho thuê',
        pendingApprovals: 'Chờ duyệt',
        monthlyRevenue: 'Doanh thu tháng',
        utilizationRate: 'Hiệu suất kho',
        trustScore: 'Điểm tín nhiệm',
        ratingAvg: 'Đánh giá trung bình',
      },
      quickActions: {
        title: 'Thao tác nhanh',
        postDevice: 'Đăng thiết bị mới',
        manageDevices: 'Quản lý kho máy',
        manageBookings: 'Duyệt yêu cầu thuê',
        blockCalendar: 'Khóa lịch bận',
        viewWallet: 'Rút tiền ký quỹ',
      },
      recentBookings: {
        title: 'Yêu cầu thuê máy gần đây',
        viewAll: 'Xem tất cả đơn',
        emptyMessage: 'Hiện chưa có yêu cầu thuê nào mới.',
      },
      kpiAndRevenueTitle: 'Tổng quan KPI & Báo cáo Doanh thu',
      kpiAndRevenueSubtitle: 'Chỉ số vận hành kho máy & Hiệu suất tăng trưởng dòng tiền',
      revenueReport: {
        title: 'Báo cáo Doanh thu',
        periodRevenuePrefix: 'Doanh thu kỳ này:',
        growthText: '+18.5%',
        growthTooltip: 'Tăng trưởng +18.5% so với kỳ trước',
        viewDetails: 'Chi tiết báo cáo',
        timeRanges: {
          '7d': '7 ngày',
          month: 'Tháng này',
          year: 'Năm nay',
        },
      },
      utilizationInsight: {
        title: 'Tỷ lệ khai thác kho',
        rateBadge: '82% lấp đầy',
        topDevicesTitle: 'Đóng góp doanh thu hàng đầu',
      },
    },

    devices: {
      title: 'Kho Thiết bị Cho thuê',
      subtitle: 'Quản lý danh sách máy, tình trạng sẵn sàng, giá niêm yết và thông số kỹ thuật',
      postBtn: 'Đăng thiết bị mới',
      searchPlaceholder: 'Tìm theo tên máy, danh mục, thương hiệu...',
      filterAll: 'Tất cả trạng thái',
      categories: {
        all: 'Tất cả danh mục',
        smartphone: 'Smartphone & Tablet',
        laptop: 'Laptop & Máy trạm',
        camera: 'Máy ảnh & Ống kính',
        drone: 'Flycam & Gimbal',
        audio: 'Tai nghe & Âm thanh',
        gaming: 'Gaming & VR',
        accessory: 'Phụ kiện',
      },
      table: {
        colDevice: 'Thiết bị & Thông tin',
        colCategory: 'Danh mục',
        colPrice: 'Giá thuê / Cọc',
        colRentals: 'Lượt thuê / Đánh giá',
        colStatus: 'Trạng thái',
        colActions: 'Hành động',
        emptyMessage: 'Không có thiết bị nào phù hợp với bộ lọc.',
      },
      status: {
        available: 'Sẵn sàng',
        rented: 'Đang cho thuê',
        maintenance: 'Bảo trì',
        hidden: 'Đang ẩn',
      },
      actions: {
        statusToggle: 'Đổi trạng thái',
        calendar: 'Khóa lịch',
        edit: 'Chỉnh sửa',
        delete: 'Gỡ bài',
      },
      modalPost: {
        title: 'Đăng tin Cho thuê Thiết bị Mới',
        nameLabel: 'Tên thiết bị',
        namePlaceholder: 'Ví dụ: Sony Alpha A7 IV Kit 28-70mm OSS...',
        brandLabel: 'Thương hiệu',
        brandPlaceholder: 'Sony, Canon, Apple, DJI...',
        categoryLabel: 'Danh mục',
        dailyRateLabel: 'Giá thuê 1 ngày (VNĐ)',
        depositLabel: 'Tiền cọc yêu cầu (VNĐ)',
        conditionLabel: 'Tình trạng máy',
        conditionPlaceholder: 'Mới 98%, nguyên seal, lens không mốc...',
        descriptionLabel: 'Mô tả chi tiết',
        descriptionPlaceholder: 'Mô tả tính năng, phụ kiện đi kèm (sạc, túi, pin dự phòng)...',
        aiPromptBtn: 'Tạo mô tả bằng Gemini AI',
        aiGenerating: 'Gemini AI đang soạn nội dung chuẩn SEO...',
        dropzoneText: 'Kéo thả ảnh thực tế vào đây hoặc bấm để chọn ảnh (Tối đa 8 ảnh)',
        cancelBtn: 'Hủy bỏ',
        submitBtn: 'Đăng thiết bị lên sàn',
      },
      toasts: {
        fetchFailed: 'Không thể tải danh sách thiết bị!',
        postSuccess: 'Đã đăng thiết bị thành công lên hệ thống!',
        statusChanged: 'Đã cập nhật trạng thái thiết bị!',
        deleteSuccess: 'Đã gỡ bài đăng thiết bị!',
      },
    },

    bookings: {
      title: 'Xử lý Yêu cầu Thuê máy',
      subtitle: 'Xem xét yêu cầu từ khách thuê, đối soát điểm tín nhiệm và bàn giao qua mã QR',
      searchPlaceholder: 'Tìm theo mã đơn, khách thuê, tên thiết bị...',
      tabs: {
        all: 'Tất cả',
        pending: 'Chờ duyệt',
        approved: 'Đã duyệt',
        active: 'Đang thuê',
        completed: 'Hoàn tất',
        rejected: 'Đã từ chối',
      },
      table: {
        colCode: 'Mã đơn',
        colDevice: 'Thiết bị thuê',
        colRenter: 'Khách thuê & Tín nhiệm',
        colDates: 'Thời gian thuê',
        colTotal: 'Tổng tiền / Cọc',
        colStatus: 'Trạng thái',
        colActions: 'Hành động',
        emptyMessage: 'Không có đơn thuê nào trong danh mục này.',
      },
      status: {
        pending: 'Chờ duyệt',
        approved: 'Đã duyệt',
        active: 'Đang thuê',
        completed: 'Hoàn tất',
        rejected: 'Đã từ chối',
        cancelled: 'Đã hủy',
      },
      actions: {
        approve: 'Duyệt đơn',
        reject: 'Từ chối',
        scanQr: 'Quét QR bàn giao',
        inspectReturn: 'Đối soát trả máy',
        viewDetail: 'Chi tiết',
      },
      modalReject: {
        title: 'Từ chối yêu cầu thuê máy',
        prompt: 'Chọn hoặc nhập lý do từ chối để thông báo đến khách thuê:',
        placeholder: 'Nhập lý do cụ thể khác...',
        cancelBtn: 'Đóng',
        confirmBtn: 'Xác nhận từ chối',
        reasons: [
          'Thiết bị cần bảo trì đột xuất',
          'Trùng lịch sử dụng cá nhân của chủ máy',
          'Điểm tín nhiệm khách thuê chưa đạt yêu cầu',
          'Khu vực nhận máy nằm ngoài bán kính phục vụ',
        ],
      },
      modalQr: {
        title: 'Quét mã QR Bàn giao Thiết bị',
        instruction: 'Mở webcam và quét mã QR đơn hàng trên điện thoại khách thuê để kích hoạt đơn:',
        simulatedBtn: 'Giả lập quét mã QR hợp lệ',
        scanning: 'Đang khởi động webcam & quét mã QR...',
        successText: 'Xác thực QR thành công! Đơn thuê đã chuyển sang trạng thái Đang cho thuê.',
        closeBtn: 'Đóng',
      },
      modalReturn: {
        title: 'Đối soát Hình ảnh & Hoàn cọc',
        instruction: 'Kiểm tra tình trạng máy thực tế đối chiếu với ảnh trước khi cho thuê:',
        beforeLabel: 'Ảnh trước khi bàn giao',
        afterLabel: 'Ảnh chụp khi trả máy',
        confirmComplete: 'Xác nhận máy nguyên vẹn & Hoàn cọc',
        claimDispute: 'Khiếu nại hư hỏng / Giữ cọc',
      },
      toasts: {
        approveSuccess: 'Đã duyệt đơn thuê thành công!',
        rejectSuccess: 'Đã từ chối đơn thuê!',
        handoverSuccess: 'Bàn giao thiết bị thành công!',
        completeSuccess: 'Đã hoàn tất đơn thuê và hoàn cọc cho khách!',
      },
    },

    calendar: {
      title: 'Lịch bận Cá nhân',
      subtitle: 'Khóa các ngày bạn cần dùng máy cá nhân để hệ thống không cho phép khách thuê đặt',
      deviceSelector: 'Chọn thiết bị:',
      hint: 'Nhấp vào ngày trong tháng để chuyển đổi giữa Sẵn sàng và Đã khóa lịch',
      legend: {
        available: 'Ngày sẵn sàng',
        blocked: 'Lịch bận cá nhân',
        rented: 'Khách đang thuê',
      },
      todayBtn: 'Hôm nay',
      clearAllBtn: 'Mở tất cả ngày',
      blockWeekendsBtn: 'Khóa thứ 7 & CN',
      blockedCountPrefix: 'Đã khóa',
      rentedCountPrefix: 'Khách thuê',
      daysSuffix: 'ngày',
      statusLocked: 'Khóa',
      statusRented: 'Đang thuê',
      statusAvailable: 'Trống',
      quickToggle: 'Khóa / Mở ngày đã chọn',
      saveSuccess: 'Đã lưu lịch bận thành công!',
    },

    analytics: {
      title: 'Báo cáo Doanh thu & Thống kê Kho',
      subtitle: 'Phân tích doanh thu theo chu kỳ, tỷ lệ khai thác và hiệu quả cho thuê của từng dòng máy',
      timeRanges: {
        '7d': '7 ngày qua',
        month: 'Tháng này',
        quarter: 'Quý này',
      },
      kpiSectionTitle: 'Tổng quan KPI',
      growthBadge: '+18.5% kỳ này',
      kpis: {
        totalRevenue: 'Tổng doanh thu thực nhận',
        totalRevenueSub: 'Đã trừ chiết khấu sàn',
        activeRentals: 'Thiết bị đang cho thuê',
        activeRentalsSub: '8 máy trong kho',
        escrowHolding: 'Tiền cọc ký quỹ an toàn',
        escrowHoldingSub: 'Bảo chứng TechShare',
        utilizationRate: 'Tỷ lệ khai thác kho máy',
        utilizationRateSub: 'Hiệu suất khai thác cao',
      },
      revenueTitle: 'Biến động Doanh thu Thuê máy',
      rentalsTitle: 'Số lượt Giao máy Thành công',
      totalRevenue: 'Tổng doanh thu',
      totalRentals: 'Tổng lượt thuê',
      avgOrderValue: 'Giá trị đơn TB',
      utilizationTitle: 'Tỷ lệ Khai thác Kho máy',
      recentRequests: {
        title: 'Yêu cầu thuê máy gần đây',
        badge: 'chờ duyệt',
        hint: 'Dữ liệu thứ yếu • Được làm mờ để tối ưu tập trung vào chỉ số tài chính',
        feePrefix: 'Tiền thuê:',
        statusPending: 'Chờ duyệt',
        viewAllBtn: 'Xem tất cả yêu cầu',
      },
    },

    wallet: {
      title: 'Ví Ký quỹ Nội bộ (Escrow Wallet)',
      subtitle: 'Bảo đảm an toàn giao dịch, số dư tiền thuê khả dụng và tiền cọc đang đóng băng',
      availableBalance: 'Số dư khả dụng',
      heldDeposit: 'Tiền cọc giữ hộ (Hold)',
      totalEarned: 'Tổng thu nhập đã nhận',
      withdrawBtn: 'Yêu cầu rút tiền',
      topupBtn: 'Nạp thêm tiền',
      transactionsTitle: 'Lịch sử Biến động Số dư',
      table: {
        colId: 'Mã GD',
        colType: 'Loại giao dịch',
        colAmount: 'Số tiền',
        colBooking: 'Mã đơn liên quan',
        colDate: 'Thời gian',
        colStatus: 'Trạng thái',
      },
      types: {
        rental_income: 'Tiền thuê thiết bị',
        deposit_hold: 'Ký quỹ tiền cọc',
        deposit_refund: 'Hoàn trả tiền cọc',
        withdraw: 'Rút tiền về tài khoản',
      },
      status: {
        success: 'Thành công',
        pending: 'Đang xử lý',
      },
    },
  },
} as const;

export default STRINGS;

